### ISSUE TITLE
Handle command_executor, desired_capabilities and browser_profile as part of the Python constructor for SauceOptions

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#126]
We need to have a constructor that can handle those capabilities above.
https://selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver

**Comment by joshmgrant** [comment]
I'm voting to defer this issue for the following reason:

- `desired_capabilities` already handles conversion to W3C options in the Python bindings as of the latest version of Selenium 3.x
- `command_executor` is a helpful abstraction that handles connecting the Remote WebDriver to appropriate endpoints. This can be a URL (string) or a `RemoteConnection` object, but in the case of a string URL, a `RemoteConnection` object is created anyway. It's not necessary for Sauce users to know this difference so we can default to requiring a string value,
- `browser_profile` must be a `FirefoxProfile` object. Using Firefox profiles with Firefox is supported by Sauce Labs but using a Firefox profile with the Python Selenium bindings and Sauce Labs is, well, less than optimal in general and so we should consider not implementing this case.

**Comment by titusfortner** [comment]
We need to support users who want to have custom values in a `RemoteConnection` object, which means allowing them to create one and pass it in with the `command_executor` kwarg to the `SauceSession` object.

I agree we do not need `desired_capabilities` or `proxy` or `options` since those are both handled by `SauceOptions`. 

I think we can skip `browser_profile` right now, because I don't believe geckodriver actually supports it, and it would belong in `SauceOptions` anyway.

I think we need to make sure `keep_alive` is set to `True` (I thought we changed that). If the default is False, Sauce needs to set it to `True`. I don't think we need to support users changing this, because it would only serve to slow everything down on Sauce.

What about `file_detector`? I think the right thing "just happens" with Remote driver, and I think we are ok without having to explicitly support the user overriding this.

**Comment by joshmgrant** [comment]
After some review, I'm still not recommending we allow users to pass in a `RemoteConnection` object and require a string URL object instead. 

The main reason is security functionality. If we allow users to pass in a `RemoteConnection` object, they can use whatever URL they'd like. This URL could include plaintext Sauce credentials such as a username and access key, which bypasses our requirement to set environment variables for these values. Since a`RemoteConnection` object is created by the Python Selenium bindings regardless, I think we should force users to provide a string instead. 

I have added an option to toggle the `resolve_ip` value should users desire to as part of the  `SauceSession` constructor. We could also add in a `keep_alive` option but this should default to `True' for improved Sauce Labs performance anyway.

**Comment by titusfortner** [comment]
I think we need to explicitly support users to pass in their own URL as some companies still use Relay.
Agree if `keep_alive` defaults to `True` than we're good.

The main reason for allowing a user to pass `RemoteConnection` directly is that presumably it is easier for them to switch from existing code to the bindings. If that's not a concern than we can keep with what you've already done in #135

**Comment by joshmgrant** [comment]
I'm going to say that allowing a user to pass `RemoteConnection` directly isn't a concern at this point @titusfortner. Of course, if this turns out to be a requested feature we can add this in post-beta. 

Also the Python bindings do allow for setting custom remote URLs in a relatively straightforward way: 

https://github.com/saucelabs/sauce_bindings/blob/master/python/tests/test_session.py#L89
