### ISSUE TITLE
Implement ability to pass in MutableCapabilities for easier adoption

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#35]
This is something we talked about that we potentially want for future iterations.   

 @Test
    public void sauceSession_takesMutableCapabilities() {
        MutableCapabilities capabilities = new MutableCapabilities();
        webDriver = new SauceSession(capabilities);
    }

**Comment by picimako** [comment]
@nadvolod @titusfortner 
I started to look into this ticket and I ran into a question.

Since `SauceSession` is supposed to take a `MutableCapabilities` as a constructor parameter, so will the underlying `SauceOptions` too, as per my understanding.
As I saw that would mean that the capabilities coming from the passed-in `MutableCapabilities` would take precedence and shouldn't be overwritten by `SauceOptions`' own config options.

```java
public void newSauceSessionFromMutableCapabilities() {
    MutableCapabilities caps = new MutableCapabilities();
    caps.setCapability("platformName", "macOS 10.13");

    SauceSession sauceSession = new SauceSession(caps);

    //When this and the undelying 'sauceOptions.toCapabilities()' is called, the new logic
    //should use "macOS 10.13" instead of the default "Windows 10" value.
    sauceSession.start();
}

public void newSauceOptionsFromMutableCapabilities() {
    MutableCapabilities caps = new MutableCapabilities();
    caps.setCapability("platformName", "macOS 10.13");

    SauceOptions sauceOptions = new SauceOptions(caps);
    sauceOptions.setPlatformName(SaucePlatform.WINDOWS_8);

    //The new logic should return "macOS 10.13" instead of "Windows 8"
    Object platformName = sauceOptions.toCapabilities().getCapability("platformName");
}
```

Is this a valid approach?

**Comment by titusfortner** [comment]
This ticket was from before the design overhaul in December, and I haven't reviewed these older tickets.

The current implementation is to have SauceOptions constructor to take specific Browser Options instances. It explicitly was decided not to accept a generic MutableCapabilities instance because Browser Options classes enforce w3c syntax where MutableCapabilities does not.

We need to have a SauceOptions instance in order to add in important Sauce related things. We could allow a Session constructor with a MutableCapabilities instance where we immediately create a SauceOptions instance and merge in the MutableCapabilities values, but as pointed out, that could result in some weird conflicts that I don't think we want to handle. 

I'm going to close out this issue as no longer desired.

@picimako thanks for you interest in this project. Are you on Selenium Org's slack? If you want to chat about ideas that might be the easiest place to find me and DM me.
